export const GET_ERRORS="GET_ERRORS";
export const GET_PROJECT_TASK="GET_PROJECT_TASK";
export const GET_USER="GET_USER";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT="GET_PRODUCT";
export const GET_PRODUCT1="GET_PRODUCT1";



